### PR TITLE
TST: add test with optional deps installed

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by ericdill** [comment]
Weird that travis took longer with pip caching

**Comment by tacaswell** [comment]
Probably the overhead of looking up / building the cache for the first time.  I just re-started them all to see if they go faster the second time.

**Comment by ericdill** [comment]
Went a little faster the second time, but still a little slower. Odd.

**Comment by tacaswell** [comment]
Yeah, cache does not help at all, nuking that.

**Comment by ericdill** [comment]
LGTM. This good to go?

**Comment by tacaswell** [comment]
yup

**Pull request merged**
