### PR TITLE
FIX: Give pop the right API so it raises the right error.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by danielballan** [comment]
attn @tacaswell

**Comment by tacaswell** [comment]
@licode Can you take a look at what is going wrong with the scripts?  I suspect this should be fixed in the citools package.

**Comment by licode** [comment]
OK, let me check this.

**Comment by licode** [comment]
Please do one-line change at travis file according to https://github.com/NSLS-II/doct/pull/7

**Comment by tacaswell** [comment]
Merging as-is because the failure is not related to the code, but the CI tools.

**Pull request merged**
